[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/opt/homebrew/bin/fish"

[font]
size = 16

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 0

[window]
decorations = "None"

[window.position]
y = 200
x = 420

[window.padding]
x = 2
y = 2

[window.dimensions]
columns = 120
lines = 39

# Colors (Kanagawa Dragon)
# Source https//github.com/rebelot/kanagawa.nvim

[colors.primary]
background = '#181616'
foreground = '#c5c9c5'

[colors.normal]
black = '#0d0c0c'
blue = '#7FB4CA'
cyan = '#7AA89F'
green = '#87a987'
magenta = '#938AA9'
red = '#E46876'
white = '#c5c9c5'
yellow = '#E6C384'

[colors.bright]
black = '#a6a69c'
blue = '#8ba4b0'
cyan = '#8ea4a2'
green = '#8a9a7b'
magenta = '#a292a3'
red = '#c4746e'
white = '#C8C093'
yellow = '#c4b28b'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'

[terminal]
